# Static Traefik configuration

defaultEntryPoints:
  - http
  - https

log:
  level: error

api:
  dashboard: true

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'

serversTransport:
  insecureSkipVerify: false

providers:
  docker:
    swarmMode: false
    watch: true
    exposedbydefault: false
  file:
    watch: true
    directory: /etc/traefik/dynamicConfiguration/
    filename: config.yml

hostResolver:
  certificatesResolvers:
    certificateResolver:
      acme:
        email: foobar@foo?foo
        storage: /letsencrypt/acme.json
        tlsChallenge: true